name: HawkScan
on:
  push:
  pull_request:
jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v3.0.0
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
