# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
        matrix:
            node-version: [18.x]
    steps:
    - uses: browser-actions/setup-chrome@latest
    #- run: chrome --version
    - run: sudo apt-get install xvfb
  #- name: Run headless test
  #    uses: GabrielBB/xvfb-action@v1
  #    with:
  #      run: npm test
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install, build and test
    #- run: npm ci
      run: |
        npm install
        npm run build --if-present
        # npm test
    - run: xvfb-run --auto-servernum npm test

